name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r dev-requirements.txt
        python setup.py install
        make clean
    - name: Lint with pylint
      run: |
        make lint
    - name: Check types with mypy
      run: |
        make mypy
    - name: Test with pytest
      run: |
        make test

