name: publish

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
    - uses: actions/checkout@v4

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v5

    - name: Build and publish to pypi
      run: uv build && uv publish --token ${{ secrets.PYPI_TOKEN }}
